sudo: false
language: python
python: 3.6
cache: pip
fast_finish: true
branches:
  only:
  - develop
  - uat
  - prod
install:
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install cfn-lint==0.77.10 sceptre sceptre-ssm-resolver
stages:
  - name: validate
  - name: deploy
    if: type = push
jobs:
  include:
    - stage: validate
      script: cfn-lint ./templates/**/*
    - stage: deploy
      script:
        - sceptre launch common --yes
        - sceptre launch $TRAVIS_BRANCH --yes
